import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { useRef } from "react";
import { gsap, ScrollTrigger } from "@/helpers/gsap";
import useIsomorphicLayoutEffect from "@/hooks/useIsomorphicLayoutEffect";
import HomeHeroSection from "@/components/Home/HeroSection";
import PitScene from "@/components/Home/PitScene";
import MPhysicsScene from "@/components/Home/MPhysicsScene";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const main = useRef<HTMLElement>(null);

  useIsomorphicLayoutEffect(() => {
    if (!main.current) return;

    const ctx = gsap.context((self: any) => {
      const h1 = main.current?.querySelectorAll("h1");

      h1?.forEach((element) => {
        const tl = gsap.timeline({
          scrollTrigger: {
            trigger: element,
            scrub: 1,
          },
        });
        tl.fromTo(element, { opacity: 0 }, { opacity: 1 });
      });
    }, main.current);

    return () => ctx.revert();
  });

  return (
    <>
      <Head>
        <title>Create Next App | Lenis Int</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`main ${inter.className}`} ref={main}>
        {/* <HomeHeroSection /> */}
        <section className="ball_pit">
          <div className="ball_canvas">
            <MPhysicsScene />
            {/* <PitScene /> */}
            {/* <BallScene /> */}
          </div>
        </section>
        <section>
          <h1>Section #2</h1>
          <p>Lorem Ipsum</p>
        </section>
        <section>
          <h1>Section #3</h1>
          <p>Lorem Ipsum</p>
        </section>
        <section>
          <h1>Section #4</h1>
          <p>Lorem Ipsum</p>
        </section>
        <section>
          <h1>Section #5</h1>
          <p>Lorem Ipsum</p>
        </section>
        <section>
          <h1>Section #6</h1>
          <p>Lorem Ipsum</p>
        </section>
      </main>
    </>
  );
}
